# -*- coding: utf-8 -*-
"""Actividad N° 7 cetaceo - Agustin Farias.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bdcOYqu_4uR6hYJwgxEW2bt3Y7gtBo8e
"""

#------------------MAMIFEROS--------------------
class Mamifero:
    def __init__(self, cantMamas, esperanzaDeVida):
        self.esperanzaDeVida = esperanzaDeVida
        self.cantMamas = cantMamas
    
    def mamar(self):
        print("Puede amamantar")
    
    def nacer(self):
        print("Nacimiento")

#------------------ANIMALES MARINOS--------------------

class AnimalMarino:
    def __init__(self, tieneBranqueas, especie):
        self.tieneBranqueas = tieneBranqueas
        self.especie = especie
    
    def nadar(self):
        print("Puede nadar")

#------------------CETACEOS--------------------

class Cetaceo(Mamifero,AnimalMarino):
    def __init__( self, notas, viveEn, peso, esperanzaDeVida,cantMamas,tieneBranqueas, especie):
      
      Mamifero.__init__(self,esperanzaDeVida, cantMamas)
      AnimalMarino.__init__(self,tieneBranqueas, especie)

      self.notas = notas
      self.viveEn = viveEn
      self.peso = peso

    def nacer(self):
        print("Nacimiento")

    def nadar(self):
        print("Puede nadar")
   
mamifero1=Mamifero(True, 10)
marino1=AnimalMarino(True, "tiburon")
cetaceo1=Cetaceo(80, "Brasil", 80, 12, True, False, "mono")

mamifero1.mamar()
marino1.nadar()
cetaceo1.nacer()